/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoUploaderRouteImport } from './routes/video-uploader'
import { Route as IndexRouteImport } from './routes/index'

const VideoUploaderRoute = VideoUploaderRouteImport.update({
  id: '/video-uploader',
  path: '/video-uploader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/video-uploader': typeof VideoUploaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/video-uploader': typeof VideoUploaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/video-uploader': typeof VideoUploaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/video-uploader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/video-uploader'
  id: '__root__' | '/' | '/video-uploader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VideoUploaderRoute: typeof VideoUploaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video-uploader': {
      id: '/video-uploader'
      path: '/video-uploader'
      fullPath: '/video-uploader'
      preLoaderRoute: typeof VideoUploaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideoUploaderRoute: VideoUploaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
